language: objective-c
osx_image: xcode8.1
cache:
  - cocoapods
before_install:
  - pod repo update --silent
script:
- xcodebuild test -workspace ContentfulPersistence.xcworkspace -scheme ContentfulPersistence_iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" | xcpretty -c
after_success:
- bundle exec slather coverage --coveralls ContentfulPersistence.xcodeproj
- pod lib lint ContentfulPersistenceSwift.podspec

